# Generated by Django 2.0.5 on 2018-05-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessagem',
            old_name='usuario',
            new_name='author',
        ),
    ]
