# Generated by Django 2.0.5 on 2018-05-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20180508_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessagem',
            old_name='messagem',
            new_name='mensagem',
        ),
    ]
