version: '3'
services:
  web:
    build: .
    command: ["python", "ava/manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    links:
      - redis
      - database
    volumes:
      - ./ava:/opt/app/ava
      - ./.venv:/usr/lib/pypy
    environment:
      - MYSQL_DATABASE=ava
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
      - MYSQL_HOST=database
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  database:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ava
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
      - MYSQL_ROOT_PASSWORD=adminpass
