# Generated by Django 2.0.5 on 2018-05-04 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180504_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Disciplina'),
            preserve_default=False,
        ),
    ]
