# Generated by Django 2.0.5 on 2018-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_turma_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
